name: Verify PR

on:
  pull_request:
    types: [opened, synchronized, reopened]
  paths:
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'pnpm-workspace.yaml'
    - 'tsup.config.ts'
    - 'eslint.config.js'
    - 'tsconfig.json'
    - '**.ts'
  workflow_dispatch:

jobs:
  verify:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*', 'latest']
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - run: pnpm install
      - run: pnpm build
      - run: pnpm check
      - run: pnpm lint
